### ISSUE TITLE
symbols function definition is void: position

### ISSUE THREAD

**Issue by CSRaghunandan** [suonlight/multi-libvterm#4]
Whenever I try to use the multi-libvterm-prev/next commnads, I get the following error: `symbols function definition is void: position`

`multi-term` also uses the same function `position`, but its not having any issues? Any idea how I can fix this?

EDIT: figured out how to fix this issue, replace `position` with `cl-position` from `cl-lib`

**Comment by suonlight** [comment]
Thank you. I fixed it by https://github.com/suonlight/multi-libvterm/commit/cf7b9943bbdb04eccd511fbb7c6e2c3bb2eff8b2
